### ISSUE TITLE
Tany) RESTful 이란 ?

### ISSUE THREAD

**Issue by juni8453** [NB993/interview-question#6]
### 💡 `개요`
- 면접 스터디 때 REST API 관련 질문을 받고 제대로 대답을 못해서 학습한 내용을 공유합니다 !
  
#### 1. `REST API` 란 ?
  - REST API 란 REST 를 기반으로 서비스 API 를 구현한 것인데, 사용할 자원을 URI 로 표현하고 이 자원을 HTTP Method 를 통해 어떻게 처리하는지 명시하도록 설계된 아키텍처입니다.
  - RESTful 하다는 것은, REST 라고 부를 수 있는 모든 제약 조건을 만족한 것을 의미합니다.
  - 사실, Uniform Interface 의 네 가지 제약 조건 중 두 가지 제약 조건을 만족하기 쉽지 않기 때문에 HTTP API 를 REST API 라고 혼동해 부르는 경우가 많습니다.

#### 2. `Uniform Interface` 란 ?
1. URI 로 자원을 식별할 수 있어야한다.
2. 식별한 자원을 어떤 HTTP Method 로 처리하는시 명시해야한다.
3. `메시지는 스스로를 설명할 수 있어야한다.`
4. `애플리케이션의 상태는 Hyperlink 를 이용해 전이 되어야 한다.`
  
#### 3. `Self-Descriptive Message`, `HATEOAS` 란 ?
- 위 제약 조건 중 1,2 번은 웬만하면 지켜지고 있지만, 문제는 3,4 번 제약 조건을 지키지 못하기 때문에 REST API 라고 할 수 없는 것입니다.
- 3번은 Self-Descriptive Message 라고 하고 4번은 HATEOAS 라고 합니다.

#### 4. `Self-Descriptive` 예시
- `수신자` 가 메세지를 이해하는데 필요한 모든 정보가 메세지 자체에 포함되어야 합니다. 요청 시 예시를 먼저 보겠습니다.
- 아래 예시는 간단한 GET 요청인데, 목적지가 빠져있기 때문에 Self-Descriptive 하지 못합니다.
```http
GET / HTTP/1.1
```

---

- 이렇게 목적지가 들어가줘야 수신자 입장에서 해당 메시지를 보고 어떤 목적을 가진 메세지인지 단번에 알 수 있습니다.
```http
GET / HTTP/1.1
Host: www.tany.com
```

---

- 이제 응답 예시를 보겠습니다.
- 이 상태라면 수신자인 클라이언트는 해당 data 가 어떤 문법으로 작성되었는지 알 방법이 없기 때문에 메세지를 이해할 수 없게 됩니다.
```http
HTTP/1.1 200 OK
{
  "id" : 1,
  "name" : "서울"
}
```

---

- 따라서 Content-Type 헤더가 필수적으로 포함되어야 합니다.
- 이제 클라이언트는 data 가 JSON 타입인 것을 알기 때문에 메세지를 이해할 수 있게 됩니다.
- 하지만 ?
```http
HTTP/1.1 200 OK
Content-Type: application/json
{
  "id" : 1,
  "name" : "서울"
}
```
---

- 위의 예시조차 완벽하게 Self-Descriptive 하다고 할 수 없습니다.
- 왜냐면 JSON 타입의 데이터라는 것을 알아도 id, name 키 값이 뭘 의미하는지 알 수 없기 때문입니다.
- 따라서 명세를 찾아서 각 키 값들의 뭘 의미하는지 알 수 있도록 Link 헤더에 확인할 수 있는 명세를 추가하는 방법이 있습니다.
- 이렇게 되면 이 응답 메시지는 클라이언트에서 완벽히 이해할 수 있는 Self-Descriptive Message 라고 할 수 있습니다.
- IANA 에 미디어 타입(Content-Type) 을 직접 등록해도 되는데요, https://sookiwi.com/posts/tech/2018/11/11/Is-it-okay-with-such-REST-APIs/ 
웬만하면 있는거 쓰는게 나을 것 같네요 ㅎㅎ..
```http
HTTP/1.1 200 OK
Content-Type: application/json
Link: <https://myProduct.com/docs/location>; rel="profile"
{
  "id" : 1,
  "name" : "서울"
}
```

---

#### 5. `HATEOAS` 예시
- HATEOAS 는 Hyperlink 를 통해 전이되어야 한다는 뜻이라고 했습니다.
- 예로, 서울 단일 조회 상태에서 서울의 세부 정보를 조회하거나 서울 인구 정보를 조회할 수 있는 자원들을 Hyperlink 로 포함시켜야 한다는 뜻입니다.
- HTML 은 <a> 태그가 존재하고 이걸 통해 다음 상태가 결정되기 때문에 HATEOAS 를 만족하지만, 문제는 JSON 인데요, 대부분 JSON 통신에서는 다음에 접근 가능한 자원 목록을 고려해 통신하지 않기 때문입니다.
```http
HTTP/1.1 200 OK
Content-Type: application/json
Link: <https://myProduct.com/docs/location>; rel="profile"
{
  "id" : 1,
  "name" : "서울"
}
```

---

- HATEOAS 또한 Link 헤더를 통해 만족시킬 수 있습니다.
- rel 속성은 https://www.iana.org/assignments/link-relations/link-relations.xhtml 에서 확인할 수 있습니다.
- 헤더에 Link 를 달수도 있지만 데이터 영역으로 자원을 포함시켜도 상관없습니다. 중요한 것은 JSON 에서 확인할 수 있냐 없냐, 클라이언트가 사용할 수 있는가 없는가 이기 때문입니다. 
```http
HTTP/1.1 200 OK
Content-Type: application/json
Link: <https://myProduct.com/docs/location>; rel="profile",</api/example/1>; rel="previous",</api/example/3>; rel="next"
```

---

#### 6. 왜 지켜야하는 조건인가 ?
- Self-Desciptive, HATEOAS 제약 조건을 지킨 RESTful API 는 메세지를 스스로 설명할 수 있기 때문에 서버나 클라이언트 변경 시에도 `언제나 해석이 가능` 하고 응답의 필드로 정의된 링크를 통해 다음 상태를 결정할 수 있기 때문에 `클라이언트가 불필요한 수정을 하지 않아도 되는 장점`이 있습니다. 
- 예를 들어, /item/{id}/detail 이란 URI 에서 /item/detail/{id} 로 URI 가 변경되더라도 응답의 필드로 정의된 링크를 통해 API 를 요청하고 있었다면, `클라이언트는 동적으로 API 를 호출하는 것` 이므로 클라이언트의 수정이 필요하지 않게 되는 것 입니다.

#### 6. 정리
- REST API 라고 불리는 API 는 거의 REST API 가 아니다.
- REST API 라고 불리기 위해선 특히 Uniform Interface 제약 조건 4가지를 모두 만족해야 한다.
- 수신자가 JSON 요청, 응답 메세지를 보고 완벽히 이해할 수 있도록 정보가 포함되어야 하며 Link 헤더로 명세 링크를 걸어두거나 헤더 또는 데이터에 다음에 접근 가능한 자원 목록을 확인할 수 있도록 하면 REST API 라고 할 수 있다. (물론  URI 에 동사형 지양 이런 것들은 지켜졌다는 가정하에)
- 찾아본 바 `HATEOAS` 를 지키기 위해 `Spring Data Rest` 라는 프레임워크 사용 또는 `RepresentationalModel` 객체 상속 등 방법이 어느 정도 있는 것 같습니다. 이 부분은 찾아보시고 테스트 해보시면 될 것 같습니다 ! ㅎㅎ

**Comment by NB993** [comment]
가려운 곳을 이렇게 긁어주시네요.. 감사합니다🥹

**Comment by juni8453** [comment]
@NB993 앗 피오 이상한게 있어서 살짝 수정했습니다 ㅎㅎ 감사합니닷
